/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.asavahtech.calculator.view;

import java.awt.Color;

/**
 *
 * @author palni
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setSize(500, 700);
        this.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.getContentPane().setBackground((new Color(56,44,187)));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        calcPanel = new javax.swing.JPanel();
        outputPanel = new javax.swing.JPanel();
        outputField = new javax.swing.JTextField();
        numOperandPanel = new javax.swing.JPanel();
        numKeyPanel = new javax.swing.JPanel();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        operandKeyPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        multBtn = new javax.swing.JButton();
        divBtn = new javax.swing.JButton();
        enterKey = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        calcPanel.setBackground(new java.awt.Color(56, 44, 187));
        calcPanel.setForeground(new java.awt.Color(56, 44, 187));
        calcPanel.setLayout(new java.awt.BorderLayout());

        outputPanel.setLayout(new java.awt.BorderLayout());

        outputField.setEditable(false);
        outputField.setBackground(new java.awt.Color(56, 44, 187));
        outputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        outputField.setPreferredSize(new java.awt.Dimension(64, 100));
        outputPanel.add(outputField, java.awt.BorderLayout.CENTER);

        calcPanel.add(outputPanel, java.awt.BorderLayout.NORTH);

        numOperandPanel.setLayout(new java.awt.BorderLayout());

        numKeyPanel.setLayout(new java.awt.GridLayout(4, 3));

        num1.setText("1");
        numKeyPanel.add(num1);

        num2.setText("2");
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        numKeyPanel.add(num2);

        num3.setText("3");
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        numKeyPanel.add(num3);

        num4.setText("4");
        numKeyPanel.add(num4);

        num5.setText("5");
        numKeyPanel.add(num5);

        num6.setText("6");
        numKeyPanel.add(num6);

        num7.setText("7");
        numKeyPanel.add(num7);

        num8.setText("8");
        numKeyPanel.add(num8);

        num9.setText("9");
        numKeyPanel.add(num9);

        num0.setText("0");
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        numKeyPanel.add(num0);

        numOperandPanel.add(numKeyPanel, java.awt.BorderLayout.CENTER);

        operandKeyPanel.setLayout(new java.awt.GridLayout(5, 1));

        addBtn.setText("+");
        operandKeyPanel.add(addBtn);

        subBtn.setText("-");
        operandKeyPanel.add(subBtn);

        multBtn.setText("*");
        operandKeyPanel.add(multBtn);

        divBtn.setText("/");
        operandKeyPanel.add(divBtn);

        enterKey.setText("=");
        enterKey.setToolTipText("");
        operandKeyPanel.add(enterKey);

        numOperandPanel.add(operandKeyPanel, java.awt.BorderLayout.EAST);

        calcPanel.add(numOperandPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(calcPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num0ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_num3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel calcPanel;
    private javax.swing.JButton divBtn;
    private javax.swing.JButton enterKey;
    private javax.swing.JButton multBtn;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JPanel numKeyPanel;
    private javax.swing.JPanel numOperandPanel;
    private javax.swing.JPanel operandKeyPanel;
    private javax.swing.JTextField outputField;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JButton subBtn;
    // End of variables declaration//GEN-END:variables
}
