/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.asavahtech.calculator.view;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.awt.GraphicsEnvironment;
import java.io.File;
import java.io.IOException;

import com.asavahtech.calculator.controller.CalcController;


/**
 *
 * @author palni
 */

public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        this.setVisible(true);
        this.setResizable(false);
        this.setSize(500, 700);
        this.setDefaultCloseOperation(javax.swing.JFrame.EXIT_ON_CLOSE);
        this.getContentPane().setBackground((new Color(56,44,187)));
        
        Font poppinsRegular;
        
        try {
            poppinsRegular = Font.createFont(Font.TRUETYPE_FONT, new File("Poppins-Regular.ttf"));
            GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
            ge.registerFont(poppinsRegular);
        } catch (IOException | FontFormatException error) {
            System.out.println(error);
        }
    }
    
    private void addToOutputPanel(String fragment) {
        outputField.setText(outputField.getText() + fragment);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //controller class init moved to bottom due to forward reference issues with the needed constructor parameter
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        calcPanel = new javax.swing.JPanel();
        outputPanel = new javax.swing.JPanel();
        outputField = new javax.swing.JTextField();
        numOperandPanel = new javax.swing.JPanel();
        numKeyPanel = new javax.swing.JPanel();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        num9 = new javax.swing.JButton();
        num0 = new javax.swing.JButton();
        decimalBtn = new javax.swing.JButton();
        backspaceBtn = new javax.swing.JButton();
        memoryAdd = new javax.swing.JButton();
        memoryMinus = new javax.swing.JButton();
        memoryRecall = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        enterBtn = new javax.swing.JButton();
        operandKeyPanel = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        subBtn = new javax.swing.JButton();
        multBtn = new javax.swing.JButton();
        divBtn = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        parenthases1 = new javax.swing.JButton();
        parenthases2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculator Jam");
        setBackground(new java.awt.Color(39, 149, 3));
        setPreferredSize(new java.awt.Dimension(166, 500));

        calcPanel.setBackground(new java.awt.Color(56, 44, 187));
        calcPanel.setForeground(new java.awt.Color(56, 44, 187));
        calcPanel.setLayout(new java.awt.BorderLayout());

        outputPanel.setPreferredSize(new java.awt.Dimension(64, 120));
        outputPanel.setLayout(new java.awt.BorderLayout());

        outputField.setEditable(false);
        outputField.setBackground(new java.awt.Color(50, 31, 171));
        outputField.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        outputField.setForeground(new java.awt.Color(225, 204, 255));
        outputField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        outputField.setBorder(null);
        outputField.setMinimumSize(new java.awt.Dimension(64, 65));
        outputField.setPreferredSize(new java.awt.Dimension(64, 120));
        outputPanel.add(outputField, java.awt.BorderLayout.CENTER);

        calcPanel.add(outputPanel, java.awt.BorderLayout.NORTH);

        numOperandPanel.setLayout(new java.awt.BorderLayout());

        numKeyPanel.setPreferredSize(new java.awt.Dimension(350, 464));
        numKeyPanel.setLayout(new java.awt.GridBagLayout());

        num1.setBackground(new java.awt.Color(80, 88, 181));
        num1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        num1.setForeground(new java.awt.Color(225, 204, 255));
        num1.setText("1");
        num1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        num1.setFocusPainted(false);
        num1.setMaximumSize(new java.awt.Dimension(64, 100));
        num1.setMinimumSize(new java.awt.Dimension(64, 35));
        num1.setPreferredSize(null);
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(num1, gridBagConstraints);

        num2.setBackground(new java.awt.Color(80, 88, 181));
        num2.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        num2.setForeground(new java.awt.Color(225, 204, 255));
        num2.setText("2");
        num2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        num2.setFocusPainted(false);
        num2.setMaximumSize(new java.awt.Dimension(64, 100));
        num2.setMinimumSize(new java.awt.Dimension(64, 35));
        num2.setPreferredSize(null);
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(num2, gridBagConstraints);

        num3.setBackground(new java.awt.Color(80, 88, 181));
        num3.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        num3.setForeground(new java.awt.Color(225, 204, 255));
        num3.setText("3");
        num3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        num3.setFocusPainted(false);
        num3.setMaximumSize(new java.awt.Dimension(64, 100));
        num3.setMinimumSize(new java.awt.Dimension(64, 35));
        num3.setPreferredSize(null);
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(num3, gridBagConstraints);

        num4.setBackground(new java.awt.Color(80, 88, 181));
        num4.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        num4.setForeground(new java.awt.Color(225, 204, 255));
        num4.setText("4");
        num4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        num4.setFocusPainted(false);
        num4.setMaximumSize(new java.awt.Dimension(64, 100));
        num4.setMinimumSize(new java.awt.Dimension(64, 35));
        num4.setPreferredSize(null);
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(num4, gridBagConstraints);

        num5.setBackground(new java.awt.Color(80, 88, 181));
        num5.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        num5.setForeground(new java.awt.Color(225, 204, 255));
        num5.setText("5");
        num5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        num5.setFocusPainted(false);
        num5.setMaximumSize(new java.awt.Dimension(64, 100));
        num5.setMinimumSize(new java.awt.Dimension(64, 35));
        num5.setPreferredSize(null);
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(num5, gridBagConstraints);

        num6.setBackground(new java.awt.Color(80, 88, 181));
        num6.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        num6.setForeground(new java.awt.Color(225, 204, 255));
        num6.setText("6");
        num6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        num6.setFocusPainted(false);
        num6.setMaximumSize(new java.awt.Dimension(64, 100));
        num6.setMinimumSize(new java.awt.Dimension(64, 35));
        num6.setPreferredSize(null);
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(num6, gridBagConstraints);

        num7.setBackground(new java.awt.Color(80, 88, 181));
        num7.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        num7.setForeground(new java.awt.Color(225, 204, 255));
        num7.setText("7");
        num7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        num7.setFocusPainted(false);
        num7.setMaximumSize(new java.awt.Dimension(64, 100));
        num7.setMinimumSize(new java.awt.Dimension(64, 35));
        num7.setPreferredSize(null);
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(num7, gridBagConstraints);

        num8.setBackground(new java.awt.Color(80, 88, 181));
        num8.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        num8.setForeground(new java.awt.Color(225, 204, 255));
        num8.setText("8");
        num8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        num8.setFocusPainted(false);
        num8.setMaximumSize(new java.awt.Dimension(64, 100));
        num8.setMinimumSize(new java.awt.Dimension(64, 35));
        num8.setPreferredSize(null);
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(num8, gridBagConstraints);

        num9.setBackground(new java.awt.Color(80, 88, 181));
        num9.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        num9.setForeground(new java.awt.Color(225, 204, 255));
        num9.setText("9");
        num9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        num9.setFocusPainted(false);
        num9.setMaximumSize(new java.awt.Dimension(64, 100));
        num9.setMinimumSize(new java.awt.Dimension(64, 35));
        num9.setPreferredSize(null);
        num9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(num9, gridBagConstraints);

        num0.setBackground(new java.awt.Color(80, 88, 181));
        num0.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        num0.setForeground(new java.awt.Color(225, 204, 255));
        num0.setText("0");
        num0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        num0.setFocusPainted(false);
        num0.setMaximumSize(new java.awt.Dimension(64, 100));
        num0.setMinimumSize(new java.awt.Dimension(64, 35));
        num0.setPreferredSize(null);
        num0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(num0, gridBagConstraints);

        decimalBtn.setBackground(new java.awt.Color(80, 88, 181));
        decimalBtn.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        decimalBtn.setForeground(new java.awt.Color(225, 204, 255));
        decimalBtn.setText(".");
        decimalBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        decimalBtn.setFocusPainted(false);
        decimalBtn.setMaximumSize(new java.awt.Dimension(64, 100));
        decimalBtn.setMinimumSize(new java.awt.Dimension(64, 35));
        decimalBtn.setPreferredSize(null);
        decimalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decimalBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(decimalBtn, gridBagConstraints);

        backspaceBtn.setBackground(new java.awt.Color(80, 88, 181));
        backspaceBtn.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        backspaceBtn.setForeground(new java.awt.Color(225, 204, 255));
        backspaceBtn.setText("CE");
        backspaceBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        backspaceBtn.setFocusPainted(false);
        backspaceBtn.setMaximumSize(new java.awt.Dimension(64, 100));
        backspaceBtn.setMinimumSize(new java.awt.Dimension(64, 35));
        backspaceBtn.setPreferredSize(new java.awt.Dimension(64, 65));
        backspaceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backspaceBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(backspaceBtn, gridBagConstraints);

        memoryAdd.setBackground(new java.awt.Color(142, 62, 164));
        memoryAdd.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        memoryAdd.setForeground(new java.awt.Color(225, 204, 255));
        memoryAdd.setText("M+");
        memoryAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        memoryAdd.setFocusPainted(false);
        memoryAdd.setMaximumSize(new java.awt.Dimension(64, 100));
        memoryAdd.setMinimumSize(new java.awt.Dimension(64, 35));
        memoryAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoryAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(memoryAdd, gridBagConstraints);

        memoryMinus.setBackground(new java.awt.Color(142, 62, 164));
        memoryMinus.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        memoryMinus.setForeground(new java.awt.Color(225, 204, 255));
        memoryMinus.setText("M-");
        memoryMinus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        memoryMinus.setFocusPainted(false);
        memoryMinus.setMaximumSize(new java.awt.Dimension(64, 100));
        memoryMinus.setMinimumSize(new java.awt.Dimension(64, 35));
        memoryMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoryMinusActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(memoryMinus, gridBagConstraints);

        memoryRecall.setBackground(new java.awt.Color(142, 62, 164));
        memoryRecall.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        memoryRecall.setForeground(new java.awt.Color(225, 204, 255));
        memoryRecall.setText("MR");
        memoryRecall.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        memoryRecall.setFocusPainted(false);
        memoryRecall.setMaximumSize(new java.awt.Dimension(64, 100));
        memoryRecall.setMinimumSize(new java.awt.Dimension(64, 35));
        memoryRecall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memoryRecallActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 26;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(memoryRecall, gridBagConstraints);

        clearBtn.setBackground(new java.awt.Color(80, 88, 181));
        clearBtn.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        clearBtn.setForeground(new java.awt.Color(225, 204, 255));
        clearBtn.setText("AC");
        clearBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        clearBtn.setFocusPainted(false);
        clearBtn.setMaximumSize(new java.awt.Dimension(64, 100));
        clearBtn.setMinimumSize(new java.awt.Dimension(64, 35));
        clearBtn.setPreferredSize(null);
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(clearBtn, gridBagConstraints);

        enterBtn.setBackground(new java.awt.Color(44, 51, 123));
        enterBtn.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        enterBtn.setForeground(new java.awt.Color(204, 204, 255));
        enterBtn.setText("=");
        enterBtn.setToolTipText("");
        enterBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(11, 2, 24)));
        enterBtn.setFocusPainted(false);
        enterBtn.setMaximumSize(new java.awt.Dimension(64, 100));
        enterBtn.setMinimumSize(new java.awt.Dimension(64, 35));
        enterBtn.setPreferredSize(null);
        enterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 15;
        gridBagConstraints.ipady = 17;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        numKeyPanel.add(enterBtn, gridBagConstraints);

        numOperandPanel.add(numKeyPanel, java.awt.BorderLayout.CENTER);

        operandKeyPanel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        operandKeyPanel.setPreferredSize(new java.awt.Dimension(110, 300));
        operandKeyPanel.setLayout(new java.awt.GridLayout(5, 1));

        addBtn.setBackground(new java.awt.Color(110, 80, 181));
        addBtn.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        addBtn.setForeground(new java.awt.Color(242, 236, 255));
        addBtn.setText("+");
        addBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addBtn.setFocusPainted(false);
        addBtn.setMinimumSize(new java.awt.Dimension(10, 75));
        addBtn.setPreferredSize(new java.awt.Dimension(50, 75));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        operandKeyPanel.add(addBtn);

        subBtn.setBackground(new java.awt.Color(110, 80, 181));
        subBtn.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        subBtn.setForeground(new java.awt.Color(242, 236, 255));
        subBtn.setText("-");
        subBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        subBtn.setFocusPainted(false);
        subBtn.setMinimumSize(null);
        subBtn.setPreferredSize(new java.awt.Dimension(5, 75));
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });
        operandKeyPanel.add(subBtn);

        multBtn.setBackground(new java.awt.Color(110, 80, 181));
        multBtn.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        multBtn.setForeground(new java.awt.Color(242, 236, 255));
        multBtn.setText("×");
        multBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        multBtn.setFocusPainted(false);
        multBtn.setMinimumSize(null);
        multBtn.setPreferredSize(new java.awt.Dimension(5, 75));
        multBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multBtnActionPerformed(evt);
            }
        });
        operandKeyPanel.add(multBtn);

        divBtn.setBackground(new java.awt.Color(110, 80, 181));
        divBtn.setFont(new java.awt.Font("Poppins ExtraBold", 0, 48)); // NOI18N
        divBtn.setForeground(new java.awt.Color(242, 236, 255));
        divBtn.setText("÷");
        divBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        divBtn.setFocusPainted(false);
        divBtn.setMinimumSize(null);
        divBtn.setPreferredSize(new java.awt.Dimension(5, 75));
        divBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divBtnActionPerformed(evt);
            }
        });
        operandKeyPanel.add(divBtn);

        jSplitPane1.setDividerLocation(55);
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(780, 0));

        parenthases1.setBackground(new java.awt.Color(110, 80, 181));
        parenthases1.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        parenthases1.setForeground(new java.awt.Color(242, 236, 255));
        parenthases1.setText("(");
        parenthases1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        parenthases1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parenthases1ActionPerformed(evt);
            }
        });
        jSplitPane1.setLeftComponent(parenthases1);

        parenthases2.setBackground(new java.awt.Color(110, 80, 181));
        parenthases2.setFont(new java.awt.Font("Poppins ExtraBold", 0, 24)); // NOI18N
        parenthases2.setForeground(new java.awt.Color(242, 236, 255));
        parenthases2.setText(")");
        parenthases2.setToolTipText("");
        parenthases2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        parenthases2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parenthases2ActionPerformed(evt);
            }
        });
        jSplitPane1.setRightComponent(parenthases2);

        operandKeyPanel.add(jSplitPane1);

        numOperandPanel.add(operandKeyPanel, java.awt.BorderLayout.EAST);

        calcPanel.add(numOperandPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(calcPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        // TODO add your handling code here:
        if(controller.isPrevTermNumber()) {
            outputField.setText("");
        }
        String output = controller.addToExpression("1");
        addToOutputPanel(output);
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        // TODO add your handling code here:
        if(controller.isPrevTermNumber()) {
            outputField.setText("");
        }
        String output = controller.addToExpression("2");
        addToOutputPanel(output);
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        // TODO add your handling code here:
        if(controller.isPrevTermNumber()) {
            outputField.setText("");
        }
        String output = controller.addToExpression("3");
        addToOutputPanel(output);
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        // TODO add your handling code here:
        if(controller.isPrevTermNumber()) {
            outputField.setText("");
        }
        String output = controller.addToExpression("4");
        addToOutputPanel(output);
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        // TODO add your handling code here:
        if(controller.isPrevTermNumber()) {
            outputField.setText("");
        }
        String output = controller.addToExpression("5");
        addToOutputPanel(output);
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        // TODO add your handling code here:
        if(controller.isPrevTermNumber()) {
            outputField.setText("");
        }
        String output = controller.addToExpression("6");
        addToOutputPanel(output);
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        // TODO add your handling code here:
        if(controller.isPrevTermNumber()) {
            outputField.setText("");
        }
        String output = controller.addToExpression("7");
        addToOutputPanel(output);
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        // TODO add your handling code here:
        if(controller.isPrevTermNumber()) {
            outputField.setText("");
        }
        String output = controller.addToExpression("8");
        addToOutputPanel(output);
    }//GEN-LAST:event_num8ActionPerformed

    private void num9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num9ActionPerformed
        // TODO add your handling code here:
        if(controller.isPrevTermNumber()) {
            outputField.setText("");
        }
        String output = controller.addToExpression("9");
        addToOutputPanel(output);
    }//GEN-LAST:event_num9ActionPerformed

    private void num0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num0ActionPerformed
        // TODO add your handling code here:
        if(controller.isPrevTermNumber()) {
            outputField.setText("");
        }
        String output = controller.addToExpression("0");
        addToOutputPanel(output);
    }//GEN-LAST:event_num0ActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        //add function to clear list of strings
        controller.clearExpression();
        outputField.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    private void decimalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decimalBtnActionPerformed
        // TODO add your handling code here:
        String output = controller.addToExpression(".");
        addToOutputPanel(output);
    }//GEN-LAST:event_decimalBtnActionPerformed

    private void backspaceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceBtnActionPerformed
        // TODO add your handling code here:
        controller.deleteLastCharacter();
        outputField.setText(outputField.getText().replaceAll(".$", ""));
    }//GEN-LAST:event_backspaceBtnActionPerformed

    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed
        // TODO add your handling code here:
        //call function that computes the expression
        java.lang.Double exprOutput = controller.computeExpression();
        if(exprOutput == null) {
            return;
        }
        outputField.setText(Double.toString(exprOutput));
    }//GEN-LAST:event_enterBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        String output = controller.addToExpression("+");
        addToOutputPanel(output);
    }//GEN-LAST:event_addBtnActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
        String output = controller.addToExpression("-");
        addToOutputPanel(output);
    }//GEN-LAST:event_subBtnActionPerformed

    private void multBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multBtnActionPerformed
        // TODO add your handling code here:
        String output = controller.addToExpression("*");
        addToOutputPanel(output);
    }//GEN-LAST:event_multBtnActionPerformed

    private void divBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divBtnActionPerformed
        // TODO add your handling code here:
        String output = controller.addToExpression("/");
        addToOutputPanel(output);
    }//GEN-LAST:event_divBtnActionPerformed

    private void memoryAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoryAddActionPerformed
        // TODO add your handling code here:
        controller.setMemNum();
    }//GEN-LAST:event_memoryAddActionPerformed

    private void memoryMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoryMinusActionPerformed
        // TODO add your handling code here:
        controller.deleteMemNum();
    }//GEN-LAST:event_memoryMinusActionPerformed

    private void memoryRecallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memoryRecallActionPerformed
        // TODO add your handling code here:
        
        String memNum = controller.addMemToExpression();
        outputField.setText(outputField.getText() + memNum);
    }//GEN-LAST:event_memoryRecallActionPerformed

    private void parenthases1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parenthases1ActionPerformed
        // TODO add your handling code here:
        String output = controller.addToExpression("(");
        addToOutputPanel(output);
    }//GEN-LAST:event_parenthases1ActionPerformed

    private void parenthases2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parenthases2ActionPerformed
        // TODO add your handling code here:
        String output = controller.addToExpression(")");
        addToOutputPanel(output);
    }//GEN-LAST:event_parenthases2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton backspaceBtn;
    private javax.swing.JPanel calcPanel;
    private javax.swing.JButton clearBtn;
    private javax.swing.JButton decimalBtn;
    private javax.swing.JButton divBtn;
    private javax.swing.JButton enterBtn;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton memoryAdd;
    private javax.swing.JButton memoryMinus;
    private javax.swing.JButton memoryRecall;
    private javax.swing.JButton multBtn;
    private javax.swing.JButton num0;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton num9;
    private javax.swing.JPanel numKeyPanel;
    private javax.swing.JPanel numOperandPanel;
    private javax.swing.JPanel operandKeyPanel;
    private javax.swing.JTextField outputField;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JButton parenthases1;
    private javax.swing.JButton parenthases2;
    private javax.swing.JButton subBtn;
    // End of variables declaration//GEN-END:variables

    //controller class init
    CalcController controller = new CalcController();
}
